lab/mysite/microblog/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView, ListView, DetailView
from django.http import HttpResponse
from models import Post
import views

urlpatterns = patterns('',
    #url(r'^$', ListView.as_view(
    #    queryset=Post.objects.order_by('-data'),
    #    context_object_name='posty',
    #    template_name="wypisz.html"
    #),

    #    name="message_list"),
    url(r'^$', views.index, name='index'),
    url(r'^dodaj/',views.add, name = 'dodaj'),
    #url(r'^dodaj/',TemplateView.as_view(template_name='dodaj.html'), name='dodaj_post')

)

#urlpatterns = patterns('',
#    url(r'^$', TemplateView.as_view(template_name='microblog/stub.html'))
#)

lab/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^blog/', include('microblog.urls', namespace='blog')),
)

lab/mysite/microblog/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    tytul = models.CharField(max_length=40)
    tekst = models.CharField(max_length=160)
    data = models.DateTimeField(auto_now=True)
    autor = models.CharField(max_length=32)

    def __unicode__(self):
        return self.tytul

lab/mysite/microblog/views.py
# Create your views here.
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib import messages
from models import Post

def add(request):
    if(request.method == 'POST'):
        tytul = request.POST.get('tytul', 0)
        tekst = request.POST.get('tekst', 0)
        autor = request.POST.get('autor', 0)
        entry = Post(title=tytul,message = tekst, nick=autor)
        entry.save()
        url = reverse('blog:index')
    else:
        #url = reverse('dodaj')
        return render(request, 'microblog/dodaj.html', {})
    return HttpResponseRedirect(url)

def index(request):
    entries = Post.objects.all()
    return render(request, 'microblog/wypisz.html', {'posty': entries})

lab/mysite/microblog/templates/microblog/dodaj.html
{% extends "base.html" %}

{% block content %}

<form action="{% url 'blog:dodaj' %}" method="POST" xmlns="http://www.w3.org/1999/html">
    <input required="required" type="text" name="tytul"></br>
    <textarea required="required" rows="5" name="tekst"></textarea></br>
    <input required="required" type="text" name="autor"></br>
    <button id="add" type="submit" class="btn">Dodaj</button>
</form>
{% endblock %}

lab/mysite/microblog/templates/microblog/stub.html
{% extends "base.html" %}

{% block content %}
Zaślepka
{% endblock %}

lab/mysite/microblog/templates/microblog/wypisz.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'blog:dodaj' %}">Dodaj post</a>
    <h3>Posty</h3>
    {% for post in posty %}
        <div class="post">
        <h3>{{ post.tytul }}</h3>
        <blockquote>
        <p>{{ post.tekst }}</p>
        <small>{{ post.data }}<br/>
        {{ post.autor }}<br/>
        </small>
        </blockquote>
        </div>
    {% endfor %}
{% endblock %}

lab/mysite/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Moja Strona</title>
    </head>
    <body>
        <div class="container">
            <div class="content">
            {% if messages %}
                {% for message in messages %}
                <p class="notification{% if message.tags %} {{ message.tags }}{% endif %}">{{ message }}</p>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
            </div>
        </div>
    </body>
</html>